/* ══════════════════════════════════════════════════════════════
   BLOG DATA — KiriTour Madagascar
   Articles SEO-optimized — internal links → /tours
══════════════════════════════════════════════════════════════ */

export const posts = [
  {
    slug: "best-time-visit-avenue-baobabs-madagascar",
    title: "Best Time to Visit the Avenue of the Baobabs (2026 Guide)",
    excerpt: "Planning to see Madagascar's most iconic sunset? Here's exactly when to visit the Avenue of the Baobabs for the best light, weather and fewest crowds.",
    cover: "https://i.ibb.co/4ZMwFVFh/IMG-20251030-WA0008.jpg",
    date: "2026-06-01",
    readTime: "6 min",
    category: "Travel Guide",
    keywords: "when to visit baobabs, avenue of the baobabs best time, morondava weather, madagascar dry season, baobabs sunset",
    relatedTour: "avenue-baobabs-betania-kimony-day-tour-morondava",
    relatedTourLabel: "Avenue of the Baobabs Day Tour",
    content: [
      { type: "p", text: "The Avenue of the Baobabs near Morondava is one of Madagascar's most photographed places — a row of ancient, towering baobab trees that glow gold at sunset. But timing your visit matters enormously. The right month and time of day can transform an ordinary stop into an unforgettable experience." },
      { type: "h2", text: "The Best Months: April to November (Dry Season)" },
      { type: "p", text: "The dry season, from April to November, is the best time to visit the Avenue of the Baobabs. Roads to Morondava and beyond are passable, skies are clear, and the famous baobab silhouettes stand out crisply against orange sunsets. The peak window of July to September offers the most reliable weather, though it is also the busiest." },
      { type: "p", text: "From December to March, the rainy season makes the dirt roads to the baobabs — and especially to Tsingy and Kirindy — difficult or impossible. Some tracks become completely impassable. If you can, plan your western Madagascar trip in the dry months." },
      { type: "h2", text: "Best Time of Day: Sunset (and Sunrise)" },
      { type: "p", text: "The Avenue earns its fame at sunset, roughly between 4:30 PM and 6:00 PM depending on the season. The low sun turns the baobabs into dramatic black silhouettes against a burning sky. Arrive at least 45 minutes early to find your spot and watch the light change." },
      { type: "p", text: "Sunrise is the quieter alternative — fewer people, soft pink light and a peaceful atmosphere. Many travellers do both: sunrise one day, sunset another." },
      { type: "tip", text: "Golden hour fills up fast in peak season. A local guide knows the best vantage points away from the crowds and the exact light timing for that month." },
      { type: "h2", text: "How Long Do You Need?" },
      { type: "p", text: "The baobabs themselves take an hour or two at sunset. But the Avenue pairs perfectly with nearby Kirindy Forest (fossa and lemurs) and the Tsingy de Bemaraha UNESCO site. A 2 to 4 day western circuit lets you combine all the highlights of the Menabe region in one trip." },
      { type: "h2", text: "Getting There" },
      { type: "p", text: "The Avenue is about 20 km north of Morondava on the road to Belo-sur-Tsiribihina — around 30 to 45 minutes by 4x4. A private guided tour handles transport, timing and photography stops so you arrive exactly when the light is best." },
    ],
  },
  {
    slug: "tsingy-de-bemaraha-travel-guide",
    title: "Tsingy de Bemaraha: Complete Travel Guide 2026",
    excerpt: "Everything you need to know to visit Tsingy de Bemaraha — Madagascar's UNESCO stone forest: how to get there, what to expect, difficulty and the best tours.",
    cover: "https://i.ibb.co/zhTgMVW2/IMG-20250915-211514.jpg",
    date: "2026-06-03",
    readTime: "8 min",
    category: "Travel Guide",
    keywords: "tsingy de bemaraha, how to visit tsingy, unesco madagascar, bekopaka, grand tsingy, tsingy tour",
    relatedTour: "tsingy-de-bemaraha-4-day-unesco-kirindy-baobabs",
    relatedTourLabel: "Tsingy de Bemaraha 4-Day Tour",
    content: [
      { type: "p", text: "Tsingy de Bemaraha is one of the most extraordinary landscapes on Earth — a vast forest of razor-sharp limestone pinnacles that rise like a stone cathedral. A UNESCO World Heritage Site, it sits in western Madagascar and rewards the adventurous traveller with hikes across suspension bridges, through caves and up to breathtaking viewpoints." },
      { type: "h2", text: "What Are the Tsingy?" },
      { type: "p", text: "The word tsingy means \"where one cannot walk barefoot\" in Malagasy — a fitting name for the needle-like limestone formations carved by millennia of rain. The park is divided into the Grand Tsingy (taller, more technical) and the Petit Tsingy (smaller, more accessible), each offering different trails and viewpoints." },
      { type: "h2", text: "How to Get to Tsingy de Bemaraha" },
      { type: "p", text: "The gateway town is Bekopaka, reached by 4x4 from Morondava via Belo-sur-Tsiribihina, with two river ferry crossings along the way. The journey takes most of a day on rough dirt roads and is only possible in the dry season, roughly April to November." },
      { type: "tip", text: "Because of the ferry crossings and remote roads, a guided 4x4 tour is by far the easiest and safest way to reach Bekopaka. Going independently is slow and risky." },
      { type: "h2", text: "How Difficult Is the Hike?" },
      { type: "p", text: "The Grand Tsingy circuit is physically demanding — you'll use fixed harnesses (via ferrata), climb ladders and squeeze through narrow passages. A reasonable level of fitness and no fear of heights helps. The Petit Tsingy is gentler and suits most visitors. Guides provide and fit all safety equipment." },
      { type: "h2", text: "What Wildlife Will You See?" },
      { type: "p", text: "Tsingy is home to endemic lemurs like the Decken's sifaka and red-fronted brown lemur, plus chameleons, birds and unique plants growing among the stone. The dramatic scenery is the star, but the wildlife makes it special." },
      { type: "h2", text: "Best Tours: Combine with Baobabs and Kirindy" },
      { type: "p", text: "Most travellers visit Tsingy as part of a 3 to 4 day western circuit that also includes the Avenue of the Baobabs and Kirindy Forest. This makes the long drive worthwhile and packs in Madagascar's western highlights — stone forest, wildlife and iconic baobabs — in a single trip." },
    ],
  },
  {
    slug: "kirindy-forest-fossa-lemurs-guide",
    title: "How to See the Fossa & Lemurs in Kirindy Forest",
    excerpt: "Kirindy Forest is the best place in Madagascar to spot the elusive fossa, plus lemurs and nocturnal wildlife. Here's how to maximise your sightings.",
    cover: "https://i.ibb.co/C5CXsY8M/IMG-20251030-WA0106.jpg",
    date: "2026-06-05",
    readTime: "6 min",
    category: "Wildlife",
    keywords: "kirindy forest, fossa madagascar, see fossa, lemurs morondava, night walk madagascar, kirindy wildlife",
    relatedTour: "kirindy-forest-fossa-lemurs-2-day-safari",
    relatedTourLabel: "Kirindy Forest 2-Day Safari",
    content: [
      { type: "p", text: "Kirindy Forest is one of Madagascar's wildlife jewels — a dry deciduous forest near Morondava that offers the best chance in the country to see the fossa, the island's largest predator. Combined with several lemur species and rich nocturnal life, it's a must for wildlife lovers visiting the west." },
      { type: "h2", text: "The Fossa: Madagascar's Apex Predator" },
      { type: "p", text: "The fossa is a cat-like carnivore found only in Madagascar and the island's top predator. Kirindy is famous as the most reliable place to see one, especially around the research camp where they are sometimes spotted during the day. Patience and an experienced guide dramatically improve your chances." },
      { type: "h2", text: "When Is the Best Time to Visit?" },
      { type: "p", text: "The dry season (April to November) is best for both access and wildlife. Fossa sightings peak during their mating season, roughly October to December, when the animals are more active and visible. The roads are also passable in these months." },
      { type: "tip", text: "Fossa are unpredictable — no guide can guarantee a sighting. Spending a night in or near Kirindy, with both dusk and dawn walks, gives you the best odds." },
      { type: "h2", text: "Lemurs and Night Walks" },
      { type: "p", text: "Kirindy hosts several lemur species, including Verreaux's sifaka and the red-fronted brown lemur by day. But the night walk is the real highlight: with a headlamp and guide, you can spot the tiny mouse lemur (one of the world's smallest primates), chameleons, geckos and nocturnal birds." },
      { type: "h2", text: "How to Visit Kirindy" },
      { type: "p", text: "Kirindy is about 60 km northeast of Morondava, roughly 2 hours by 4x4, often combined with a sunset stop at the Avenue of the Baobabs on the way. A 1-day trip is possible, but staying overnight for a night walk and an early morning walk maximises wildlife sightings." },
    ],
  },
];

export const POST_BY_SLUG = Object.fromEntries(posts.map((p) => [p.slug, p]));